apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: teachua
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: ghcr.io/riznicenkoa/teachua-backend:1
          imagePullPolicy: IfNotPresent
          command: ["java","-jar","/app.war"]
          env:
            - { name: JAVA_OPTS,        value: "-Xmx384m" }
            - { name: JDBC_DRIVER,      value: org.mariadb.jdbc.Driver }
            - { name: DATASOURCE_URL,   value: jdbc:mariadb://mariadb:3306/teachua2 }
            - { name: DATASOURCE_USER,  valueFrom: { secretKeyRef: { name: mariadb-secret, key: MARIADB_USER } } }
            - { name: DATASOURCE_PASSWORD, valueFrom: { secretKeyRef: { name: mariadb-secret, key: MARIADB_PASSWORD } } }
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { memory: "512Mi", cpu: "300m" }
            limits:   { memory: "900Mi", cpu: "800m" }
          readinessProbe:
            httpGet: { path: /dev/api/categories, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
