apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: teachua
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      log_level: warn
    common:
      ring:
        kvstore: { store: inmemory }
        instance_id: loki-0
      replication_factor: 1
      path_prefix: /loki
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
      filesystem:
        directory: /loki/chunks
    limits_config:
      retention_period: 168h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
      retention_enabled: true
