apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: teachua
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: TeachUA_root_2026!
  MARIADB_DATABASE: teachua2
  MARIADB_USER: teachua
  MARIADB_PASSWORD: TeachUA_dev_2026!
