apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: teachua
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: ghcr.io/riznicenkoa/teachua-frontend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - { name: conf, mountPath: /etc/nginx/conf.d }
          resources:
            requests: { memory: "64Mi", cpu: "50m" }
            limits:   { memory: "128Mi", cpu: "200m" }
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile: { type: RuntimeDefault }
            capabilities: { drop: ["ALL"], add: ["CHOWN","SETGID","SETUID","NET_BIND_SERVICE"] }
      volumes:
        - name: conf
          configMap:
            name: teachua-frontend-conf
